#!/usr/bin/env python
"""Generate static/tw-accent.css — a plain-CSS backstop for the accent utility
classes used in templates.

Why: the Tailwind Play CDN (cdn.tailwindcss.com) generates only the classes it
sees in the DOM at scan time. Accent utilities that appear ONLY inside an HTMX
innerHTML swap (e.g. the wiki panel) can be missed — worst on Safari/WebKit,
which then renders white-on-white. This emits those classes unconditionally so
they exist regardless of the runtime JIT.

Scope: the non-slate accent palette only (slate/white are handled by the CDN at
initial scan and are remapped under html.dark — we must NOT shadow those). Covers
bg-/text-/border- + the hover: variant + /opacity modifiers, for exactly the
(color, shade) pairs found in templates/.

Run:  python scripts/gen_accent_css.py
Drift guard: tests/test_accent_css.py fails if a template uses an accent class
this file doesn't define.
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
OUT = ROOT / "static" / "tw-accent.css"

# Tailwind v3 default palette for the accent families used in this app.
PALETTE: dict[str, dict[int, str]] = {
    "violet": {50: "#f5f3ff", 100: "#ede9fe", 200: "#ddd6fe", 300: "#c4b5fd", 400: "#a78bfa", 500: "#8b5cf6", 600: "#7c3aed", 700: "#6d28d9", 800: "#5b21b6", 900: "#4c1d95"},
    "sky":    {50: "#f0f9ff", 100: "#e0f2fe", 200: "#bae6fd", 300: "#7dd3fc", 400: "#38bdf8", 500: "#0ea5e9", 600: "#0284c7", 700: "#0369a1", 800: "#075985", 900: "#0c4a6e"},
    "rose":   {50: "#fff1f2", 100: "#ffe4e6", 200: "#fecdd3", 300: "#fda4af", 400: "#fb7185", 500: "#f43f5e", 600: "#e11d48", 700: "#be123c", 800: "#9f1239", 900: "#881337"},
    "emerald":{50: "#ecfdf5", 100: "#d1fae5", 200: "#a7f3d0", 300: "#6ee7b7", 400: "#34d399", 500: "#10b981", 600: "#059669", 700: "#047857", 800: "#065f46", 900: "#064e3b"},
    "amber":  {50: "#fffbeb", 100: "#fef3c7", 200: "#fde68a", 300: "#fcd34d", 400: "#fbbf24", 500: "#f59e0b", 600: "#d97706", 700: "#b45309", 800: "#92400e", 900: "#78350f"},
    "indigo": {50: "#eef2ff", 100: "#e0e7ff", 200: "#c7d2fe", 300: "#a5b4fc", 400: "#818cf8", 500: "#6366f1", 600: "#4f46e5", 700: "#4338ca", 800: "#3730a3", 900: "#312e81"},
    "orange": {50: "#fff7ed", 100: "#ffedd5", 200: "#fed7aa", 300: "#fdba74", 400: "#fb923c", 500: "#f97316", 600: "#ea580c", 700: "#c2410c", 800: "#9a3412", 900: "#7c2d12"},
    "green":  {50: "#f0fdf4", 100: "#dcfce7", 200: "#bbf7d0", 300: "#86efac", 400: "#4ade80", 500: "#22c55e", 600: "#16a34a", 700: "#15803d", 800: "#166534", 900: "#14532d"},
}
PROP = {"bg": "background-color", "text": "color", "border": "border-color"}
FAMILIES = "|".join(PALETTE)
# (hover:)? (bg|text|border) - family - shade (/opacity)?
TOKEN_RE = re.compile(rf"(hover:)?(bg|text|border)-({FAMILIES})-(\d{{2,3}})(?:/(\d{{1,3}}))?")


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def collect_tokens() -> set[tuple]:
    """Every (hover, prop, family, shade, opacity) tuple used in templates."""
    found: set[tuple] = set()
    for f in TEMPLATES.rglob("*.html"):
        for m in TOKEN_RE.finditer(f.read_text(encoding="utf-8")):
            hover, prop, fam, shade, op = m.groups()
            found.add((bool(hover), prop, fam, int(shade), int(op) if op else None))
    return found


def _css_class(hover: bool, prop: str, fam: str, shade: int, op: int | None) -> str:
    """The escaped selector for a utility token, e.g. .hover\\:bg-emerald-700:hover"""
    cls = f"{prop}-{fam}-{shade}" + (f"/{op}" if op is not None else "")
    cls = cls.replace("/", r"\/")                      # escape opacity slash
    if hover:
        return rf".hover\:{cls}:hover"
    return f".{cls}"


def _value(prop: str, fam: str, shade: int, op: int | None) -> str:
    hexv = PALETTE[fam][shade]
    if op is None:
        return hexv
    r, g, b = _hex_to_rgb(hexv)
    return f"rgba({r}, {g}, {b}, {op / 100:g})"


def build_css(tokens: set[tuple]) -> str:
    lines = [
        "/* GENERATED by scripts/gen_accent_css.py — DO NOT EDIT BY HAND.",
        "   Plain-CSS backstop for accent utilities the Tailwind Play CDN may miss",
        "   in HTMX-swapped fragments (white-on-white on Safari). Regenerate after",
        "   adding accent classes; tests/test_accent_css.py guards drift. */",
    ]
    keyed = sorted(tokens, key=lambda t: (t[1], t[2], t[3], -1 if t[4] is None else t[4], t[0]))
    for hover, prop, fam, shade, op in keyed:
        sel = _css_class(hover, prop, fam, shade, op)
        lines.append(f"{sel}{{{PROP[prop]}:{_value(prop, fam, shade, op)}}}")
    return "\n".join(lines) + "\n"


def main() -> None:
    tokens = collect_tokens()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_css(tokens), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(tokens)} accent rules.")


if __name__ == "__main__":
    main()
